mysql:
  hostname: 8.138.31.44
  port: 3307
  database: school
  username: root
  password: 123

redis:
  hostname: 8.138.31.44
  port: 6380
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 100